// Generated by CoffeeScript 1.4.0
(function() {

  Backbone.sync = function() {};

  module('Backpack.attach');

  test('attach and detach', function() {
    var handler, obj;
    obj = {
      counter: 0,
      event: function() {}
    };
    handler = Backpack.attach(obj, 'event', function() {
      obj.counter++;
    });
    obj.event();
    equal(obj.counter, 1, 'counter should be incremented.');
    obj.event();
    obj.event();
    obj.event();
    obj.event();
    equal(obj.counter, 5, 'counter should be incremented five times.');
    handler.detach();
    obj.event();
    equal(obj.counter, 5, 'counter should not be incremented.');
    obj.event();
    obj.event();
    obj.event();
    equal(obj.counter, 5, 'counter should not be incremented.');
  });

  test('attach with arguments', function() {
    var obj;
    obj = {
      counter: 0,
      event: function(arg1, arg2) {}
    };
    Backpack.attach(obj, 'event', function(arg1, arg2) {
      equal(arg1, 'x', 'first argument should be passed in callback function');
      equal(arg2, 2, 'second argument should be passed in callback function');
    });
    obj.event('x', 2);
  });

  test('attach multiple events', function() {
    var handler1, handler2, obj;
    obj = {
      counter1: 0,
      counter2: 0,
      event: function() {}
    };
    handler1 = Backpack.attach(obj, 'event', function() {
      obj.counter1++;
    });
    handler2 = Backpack.attach(obj, 'event', function() {
      obj.counter2++;
    });
    obj.event();
    equal(obj.counter1, 1, 'counter1 should be incremented.');
    equal(obj.counter2, 1, 'counter2 should be incremented.');
    obj.event();
    obj.event();
    obj.event();
    obj.event();
    equal(obj.counter1, 5, 'counter1 should be incremented five times.');
    equal(obj.counter2, 5, 'counter2 should be incremented five times.');
    handler2.detach();
    obj.event();
    equal(obj.counter1, 6, 'counter1 should be incremented six times.');
    equal(obj.counter2, 5, 'counter2 should be incremented five times.');
    handler1.detach();
    obj.event();
    equal(obj.counter1, 6, 'counter1 should be incremented six times.');
    equal(obj.counter2, 5, 'counter2 should be incremented five times.');
  });

  module('Backpack.Model');

  test('extend with plugins', function() {
    var TestModel, model, testPlugin;
    testPlugin = {
      setup: function() {
        this.name = 'hello';
      },
      cleanup: function() {
        this.name = 'bye';
      }
    };
    TestModel = Backpack.Model.extend({
      plugins: [testPlugin]
    });
    model = new TestModel();
    equal(model.name, 'hello', 'setup called');
    model.destroy();
    return equal(model.name, 'bye', 'cleanup called');
  });

  test('extend with multiple plugins', function() {
    var TestModel, model, testPlugin1, testPlugin2;
    testPlugin1 = {
      setup: function() {
        this.name1 = 'hello';
      },
      cleanup: function() {
        this.name1 = 'bye';
      }
    };
    testPlugin2 = {
      setup: function() {
        this.name2 = 'konichiwa';
      },
      cleanup: function() {
        this.name2 = 'sayonara';
      }
    };
    TestModel = Backpack.Model.extend({
      plugins: [testPlugin1, testPlugin2]
    });
    model = new TestModel();
    equal(model.name1, 'hello', 'setup called for first plugin');
    equal(model.name2, 'konichiwa', 'setup called for second plugin');
    model.destroy();
    equal(model.name1, 'bye', 'cleanup called for first plugin');
    return equal(model.name2, 'sayonara', 'cleanup called for second plugin');
  });

  test('initialize with plugins', function() {
    var model, testPlugin;
    testPlugin = {
      setup: function() {
        this.name = 'hello';
      },
      cleanup: function() {
        this.name = 'bye';
      }
    };
    model = new Backpack.Model(null, {
      plugins: [testPlugin]
    });
    equal(model.name, 'hello', 'setup called');
    model.destroy();
    return equal(model.name, 'bye', 'cleanup called');
  });

  test('initialize with multiple plugins', function() {
    var model, testPlugin1, testPlugin2;
    testPlugin1 = {
      setup: function() {
        this.name1 = 'hello';
      },
      cleanup: function() {
        this.name1 = 'bye';
      }
    };
    testPlugin2 = {
      setup: function() {
        this.name2 = 'konichiwa';
      },
      cleanup: function() {
        this.name2 = 'sayonara';
      }
    };
    model = new Backpack.Model(null, {
      plugins: [testPlugin1, testPlugin2]
    });
    equal(model.name1, 'hello', 'setup called for first plugin');
    equal(model.name2, 'konichiwa', 'setup called for second plugin');
    model.destroy();
    equal(model.name1, 'bye', 'cleanup called for first plugin');
    return equal(model.name2, 'sayonara', 'cleanup called for second plugin');
  });

  test('override extend plugins with initialize plugins', function() {
    var TestModel, model, testPlugin1, testPlugin2;
    testPlugin1 = {
      setup: function() {
        this.name1 = 'hello';
      },
      cleanup: function() {
        this.name1 = 'bye';
      }
    };
    testPlugin2 = {
      setup: function() {
        this.name2 = 'konichiwa';
      },
      cleanup: function() {
        this.name2 = 'sayonara';
      }
    };
    TestModel = Backpack.Model.extend({
      plugins: [testPlugin1]
    });
    model = new TestModel(null, {
      plugins: [testPlugin2]
    });
    notEqual(model.name1, 'hello', 'setup not called for extend plugin');
    equal(model.name2, 'konichiwa', 'setup called for initialize plugin');
    model.destroy();
    notEqual(model.name1, 'bye', 'cleanup not called for extend plugin');
    return equal(model.name2, 'sayonara', 'cleanup called for initialize plugin');
  });

}).call(this);
