// Generated by CoffeeScript 1.4.0
(function() {

  Backpack.testDefs = [
    {
      "class": Backpack.Model,
      name: 'Backpack.Model',
      createInstance: function(options) {
        return new Backpack.Model(null, options);
      }
    }, {
      "class": Backpack.Collection,
      name: 'Backpack.Collection',
      createInstance: function(options) {
        return new Backpack.Collection(null, options);
      }
    }, {
      "class": Backpack.View,
      name: 'Backpack.View',
      createInstance: function(options) {
        return new Backpack.View(options);
      }
    }, {
      "class": Backpack.Class,
      name: 'Backpack.Class',
      createInstance: function(options) {
        return new Backpack.Class(options);
      }
    }
  ];

  Backpack.isHidden = function(node) {
    console.log(node.width() + ", " + node.height());
    return node.width() === 0 && node.height() === 0;
  };

}).call(this);
