// Generated by CoffeeScript 1.6.2
(function() {
  Backpack.testDefs = [
    {
      "class": Backpack.Model,
      name: 'Backpack.Model',
      createInstance: function(options) {
        return new Backpack.Model(null, options);
      }
    }, {
      "class": Backpack.Collection,
      name: 'Backpack.Collection',
      createInstance: function(options) {
        return new Backpack.Collection(null, options);
      }
    }, {
      "class": Backpack.View,
      name: 'Backpack.View',
      createInstance: function(options) {
        return new Backpack.View(options);
      }
    }, {
      "class": Backpack.Class,
      name: 'Backpack.Class',
      createInstance: function(options) {
        return new Backpack.Class(options);
      }
    }
  ];

}).call(this);
