// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty;

  define(['jQuery', 'Underscore', 'Backbone', 'backpack/plugins/Subscribable', 'backpack/plugins/Publishable'], function($, _, Backbone, Subscribable, Publishable) {
    var cleanup, setup;
    setup = function(self, options) {
      var key, plugins, setups, value;
      if (options == null) {
        options = {};
      }
      for (key in options) {
        if (!__hasProp.call(options, key)) continue;
        value = options[key];
        self[key] = _.isFunction(value) ? _.bind(value, self) : value;
      }
      self.cleanups = [];
      setups = [];
      plugins = [Subscribable, Publishable];
      if (options != null ? options.plugins : void 0) {
        plugins = plugins.concat(options.plugins);
      }
      _.each(plugins, function(pi) {
        var cu, su;
        su = pi.setup;
        cu = pi.cleanup;
        for (key in pi) {
          if (!__hasProp.call(pi, key)) continue;
          value = pi[key];
          if (key !== 'setup' && key !== 'cleanup') {
            self[key] = _.isFunction(value) ? _.bind(value, self) : value;
          }
        }
        if (su) {
          setups.push(su);
        }
        if (cu) {
          self.cleanups.push(cu);
        }
      });
      _.each(setups, function(su) {
        su.apply(self);
      });
    };
    cleanup = function(self) {
      _.each(self.cleanups, function(cu) {
        cu.apply(self);
      });
    };
    return {
      Model: Backbone.Model.extend({
        initialize: function(attributes, options) {
          Backbone.Model.prototype.initialize.apply(this, arguments);
          setup(this, options);
        },
        destroy: function(options) {
          cleanup(this);
          Backbone.Model.prototype.destroy.apply(this, arguments);
        }
      }),
      Collection: Backbone.Collection.extend({
        initialize: function(models, options) {
          Backbone.Collection.prototype.initialize.apply(this, arguments);
          setup(this, options);
        },
        destroy: function() {
          cleanup(this);
        }
      }),
      View: Backbone.View.extend({
        initialize: function(options) {
          Backbone.View.prototype.initialize.apply(this, arguments);
          setup(this, options);
        },
        remove: function() {
          cleanup(this);
          Backbone.View.prototype.remove.apply(this, arguments);
        }
      })
    };
  });

}).call(this);
