// Generated by CoffeeScript 1.4.0
(function() {

  Backpack.Container = {
    setup: function() {
      if (!this.containerNode) {
        this.containerNode = this.$el;
      }
      if (!this.children) {
        this.children = [];
      }
    },
    getChild: function(index) {
      return this.children[index];
    },
    addView: function(view) {
      this.containerNode.append(view.$el);
    },
    addChild: function(view) {
      this.addView(view);
      this.children.push(view);
    },
    clearChildren: function() {
      var i, _i, _ref;
      for (i = _i = _ref = this.children.length - 1; _i >= 0; i = _i += -1) {
        this.removeChild(i);
      }
    },
    removeChild: function(index) {
      this.children[index].remove();
      this.children.splice(index, 1);
    },
    filterChildren: function(options) {
      _.filter(this.children, function(view) {
        if (view.model.filter(options)) {
          view.$el.show();
        } else {
          view.$el.hide();
        }
      });
    },
    cleanup: function() {
      this.clearChildren();
    }
  };

}).call(this);
