// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty;

  define(['Underscore', 'Backbone'], function(_, Backbone) {
    var insertTrigger;
    insertTrigger = function(self, key, value) {
      var newFunc, origFunc;
      if (_.isFunction(self[key])) {
        origFunc = self[key];
        newFunc = function() {
          var args, ret;
          ret = origFunc.apply(this, arguments);
          args = Array.splice.call(arguments, 0, 0, value);
          Backbone.trigger.apply(this, args);
          return ret;
        };
        self[key] = _.bind(newFunc, self);
      }
    };
    return {
      setup: function() {
        var key, value, _ref;
        if (this.publishers) {
          _ref = this.publishers;
          for (key in _ref) {
            if (!__hasProp.call(_ref, key)) continue;
            value = _ref[key];
            insertTrigger(this, key, value);
          }
        }
      }
    };
  });

}).call(this);
