// Generated by CoffeeScript 1.4.0
(function() {

  Backpack.Sortable = {
    setup: function() {
      if (this.sortable !== false) {
        this.setSortable(true);
      }
    },
    setSortable: function(isSortable) {
      var _this = this;
      if (isSortable) {
        if (this._sortableInit) {
          this.$el.sortable("enable");
        } else {
          this.$el.sortable({
            start: function(event, ui) {
              ui.item.startIndex = ui.item.index();
            },
            stop: function(event, ui) {
              var collection, model, newIndex;
              collection = _this.collection;
              model = collection.at(ui.item.startIndex);
              newIndex = ui.item.index();
              collection.remove(model);
              collection.add(model, {
                at: newIndex
              });
            }
          });
          this._sortableInit = true;
        }
      } else {
        if (this._sortableInit) {
          this.$el.sortable("disable");
        }
      }
    },
    cleanup: function() {
      if (this._sortableInit) {
        this.$el.sortable("destroy");
      }
    }
  };

}).call(this);
