// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty;

  define(['Underscore', 'Backbone'], function(_, Backbone) {
    return {
      setup: function() {
        var cb, key, value, _ref;
        if (this.subscribers) {
          _ref = this.subscribers;
          for (key in _ref) {
            if (!__hasProp.call(_ref, key)) continue;
            value = _ref[key];
            cb = _.isString(value) ? this[value] : value;
            Backbone.on(key, cb, this);
          }
        }
      },
      cleanup: function() {
        var cb, key, value, _ref;
        if (this.subscribers) {
          _ref = this.subscribers;
          for (key in _ref) {
            if (!__hasProp.call(_ref, key)) continue;
            value = _ref[key];
            cb = _.isString(value) ? this[value] : value;
            Backbone.off(key, cb, this);
          }
        }
      }
    };
  });

}).call(this);
