// Generated by CoffeeScript 1.4.0
(function() {

  Backpack.ListView = Backpack.View.extend({
    itemClass: Backbone.View,
    initialize: function(options) {
      Backpack.View.prototype.initialize.apply(this, arguments);
      if (options.itemClass) {
        this.itemClass = options.itemClass;
      }
      this.collection.on("add remove reset", this.render, this);
      this._views = [];
    },
    render: function() {
      var models;
      models = this.collection.models;
      this.clearChildren();
      if (models.length > 0) {
        _.each(models, this.addChild, this);
      } else {
        this.$el.html("No Items");
      }
      return this;
    },
    getChild: function(index) {
      return this._views[index];
    },
    addChild: function(model) {
      var view;
      view = new this.itemClass({
        model: model
      });
      this.$el.append(view.render().$el);
      this._views.push(view);
    },
    clearChildren: function() {
      var i, _i, _ref;
      for (i = _i = _ref = this._views.length - 1; _i >= 0; i = _i += -1) {
        this.removeChild(i);
      }
    },
    removeChild: function(index) {
      this._views[index].remove();
      this._views.splice(index, 1);
    },
    filterChildren: function(options) {
      _.filter(this._views, function(view) {
        if (view.model.filter(options)) {
          view.$el.show();
        } else {
          view.$el.hide();
        }
      });
    },
    remove: function() {
      this.collection.off("add remove reset", this.render);
      Backpack.View.prototype.remove.call(this);
    }
  });

}).call(this);
